# Generated by Django 3.2.2 on 2022-09-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_auto_20220913_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
